//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webdemofinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int IDvoucher { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<int> minbill { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
